name: Markdown Linter

on: [push]

jobs:
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run my custom proselint action
        uses: ./.github/actions/proselint-action
